ALTER TABLE tb_bookmark ALTER COLUMN register_date TYPE timestamp with time zone USING register_date::timestamp with time zone;
ALTER TABLE tb_bookmark ALTER COLUMN register_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_calendar ALTER COLUMN calendar_date TYPE timestamp with time zone USING calendar_date::timestamp with time zone;
ALTER TABLE tb_calendar ALTER COLUMN register_date TYPE timestamp with time zone USING register_date::timestamp with time zone;
ALTER TABLE tb_calendar ALTER COLUMN register_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_food ALTER COLUMN register_date TYPE timestamp with time zone USING register_date::timestamp with time zone;
ALTER TABLE tb_food ALTER COLUMN register_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_notice ALTER COLUMN register_date TYPE timestamp with time zone USING register_date::timestamp with time zone;
ALTER TABLE tb_notice ALTER COLUMN register_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_notice ALTER COLUMN modified_date TYPE timestamp with time zone USING modified_date::timestamp with time zone;
ALTER TABLE tb_notice ALTER COLUMN modified_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_notice ALTER COLUMN start_date TYPE timestamp with time zone USING start_date::timestamp with time zone;
ALTER TABLE tb_notice ALTER COLUMN end_date TYPE timestamp with time zone USING end_date::timestamp with time zone;
ALTER TABLE tb_personal_taste ALTER COLUMN register_date TYPE timestamp with time zone USING register_date::timestamp with time zone;
ALTER TABLE tb_personal_taste ALTER COLUMN register_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_restaurant ALTER COLUMN register_date TYPE timestamp with time zone USING register_date::timestamp with time zone;
ALTER TABLE tb_restaurant ALTER COLUMN register_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_review ALTER COLUMN register_date TYPE timestamp with time zone USING register_date::timestamp with time zone;
ALTER TABLE tb_review ALTER COLUMN register_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_search_mnt ALTER COLUMN valid_date TYPE timestamp with time zone USING valid_date::timestamp with time zone;
ALTER TABLE tb_search_mnt ALTER COLUMN register_date TYPE timestamp with time zone USING register_date::timestamp with time zone;
ALTER TABLE tb_search_mnt ALTER COLUMN register_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_tag_history ALTER COLUMN register_date TYPE timestamp with time zone USING register_date::timestamp with time zone;
ALTER TABLE tb_tag_history ALTER COLUMN register_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_user ALTER COLUMN register_date TYPE timestamp with time zone USING register_date::timestamp with time zone;
ALTER TABLE tb_user ALTER COLUMN register_date SET DEFAULT CURRENT_TIMESTAMP;
